#!/usr/bin/env python3
"""Complete enumeration of [[14,3]] stabilizer codes invariant under a
fixed-point-free automorphism of order 7 (= two disjoint 7-cycles on qubits;
any such permutation is conjugate to the standard one, and distance is
permutation-invariant, so this covers the whole equivalence class).

Qubits 0..6 = block 1, 7..13 = block 2; sigma shifts each block by one.
x^7+1 = (x+1) p q with p = x^3+x+1, q = x^3+x^2+1 (squarefree -> semisimple).
V = F2^28 decomposes as V1 (dim 4, trivial) + Vp (K^4, K=F8) + Vq (K'^4).
Slots of the rank-4 module: (a1, a2, b1, b2).
Invariant subspace = U0 + Up + Uq, dims d0 + 3 dp + 3 dq = 11 with
d0 <= 4, so d0 = 2 and dp + dq = 3.
Isotropy: V1 pairs with itself (U0 must be isotropic = Lagrangian);
Vp pairs with Vq (reciprocal(p) = q): sp(Up, Uq) = 0; Vp x Vp and Vq x Vq
vanish (asserted).

Output: candidates as 11 hex words per line for check1435 batch 11.
Optional argv[1] = dp restricts to that dp value (for sharding).
"""
import sys
from itertools import combinations

N7 = 7
M7 = (1 << N7) - 1

def pmul(a, b):
    r = 0
    while b:
        if b & 1:
            r ^= a
        a <<= 1
        b >>= 1
    return r

def pdeg(a):
    return a.bit_length() - 1

def pdivmod(a, b):
    q = 0
    db = pdeg(b)
    while a and pdeg(a) >= db:
        s = pdeg(a) - db
        q ^= 1 << s
        a ^= b << s
    return q, a

def pmod(a, b):
    return pdivmod(a, b)[1]

def pxgcd(a, b):
    r0, r1 = a, b
    s0, s1 = 1, 0
    t0, t1 = 0, 1
    while r1:
        qq, rr = pdivmod(r0, r1)
        r0, r1 = r1, rr
        s0, s1 = s1, s0 ^ pmul(qq, s1)
        t0, t1 = t1, t0 ^ pmul(qq, t1)
    return r0, s0, t0

X71 = (1 << 7) | 1
P = 0b1011
Q = 0b1101
assert pmul(0b11, pmul(P, Q)) == X71

def idem(F):
    G = pdivmod(X71, F)[0]
    g, u, v = pxgcd(G, F)
    assert g == 1
    e = pmod(pmul(u, G), X71)
    assert pmod(pmul(e, e), X71) == e
    return e

E1, EP, EQ = idem(0b11), idem(P), idem(Q)
assert E1 ^ EP ^ EQ == 1

def mul7(a, b):
    return pmod(pmul(a, b), X71)

# field K = ideal generated by EP (8 elements), similarly K'
def field_elems(e):
    # ideal generated by the idempotent e = { e*t : t in R7 }
    return sorted({mul7(e, t) for t in range(128)})

KP = field_elems(EP)
KQ = field_elems(EQ)
assert len(KP) == 8 and len(KQ) == 8

# F2-basis of each field (as 7-bit words)
def fbasis(e):
    return [e, mul7(e, 0b10), mul7(e, 0b100)]  # e, x e, x^2 e

BKP = fbasis(EP)
BKQ = fbasis(EQ)

# embed 7-bit word into slot s of 28-bit vector; slots (a1,a2,b1,b2)
def embed(c, s):
    return c << (7 * s)

def sp(u, v):
    MASKA = (1 << 14) - 1
    ua, ub = u & MASKA, u >> 14
    va, vb = v & MASKA, v >> 14
    return (bin(ua & vb).count('1') + bin(ub & va).count('1')) & 1

# --- trivial component: Lagrangians ---
J = M7  # all-ones = idempotent for x+1 times ... E1 should be J
assert E1 == J
triv = [embed(J, s) for s in range(4)]
# all 2-dim subspaces of span(triv) that are isotropic
lagr = []
seen = set()
for c1 in range(1, 16):
    for c2 in range(c1 + 1, 16):
        if c2 == c1:
            continue
        spanset = frozenset((0, c1, c2, c1 ^ c2))
        if spanset in seen:
            continue
        seen.add(spanset)
        v1 = 0
        v2 = 0
        for s in range(4):
            if c1 >> s & 1:
                v1 ^= triv[s]
            if c2 >> s & 1:
                v2 ^= triv[s]
        if sp(v1, v2) == 0:
            lagr.append((v1, v2))
print(f"trivial: {len(seen)} planes, {len(lagr)} isotropic", file=sys.stderr)

# --- K-subspaces of K^4 as RREF matrices over the field ---
def subspaces(K, dim):
    """yield lists of rows; each row = 4-tuple of field elements (7-bit words),
    in RREF over the field K (pivot = first nonzero = identity elt of K)."""
    e = [k for k in K if k and mul7(k, k) == k][0]  # identity of the field
    Knz = [k for k in K if k]
    out = []
    from itertools import combinations as C
    idx = range(4)
    for pivs in C(idx, dim):
        # free positions: for row i (pivot col pivs[i]): cols > pivs[i], not a pivot col
        freepos = []
        for i in range(dim):
            fp = [c for c in idx if c > pivs[i] and c not in pivs]
            freepos.append(fp)
        nfree = sum(len(f) for f in freepos)
        # iterate all assignments of K to free positions
        def rec(i, rows):
            if i == dim:
                out.append([tuple(r) for r in rows])
                return
            fps = freepos[i]
            def rec2(j, row):
                if j == len(fps):
                    rec(i + 1, rows + [row])
                    return
                for k in K:
                    r2 = row[:]
                    r2[fps[j]] = k
                    rec2(j + 1, r2)
            base = [0, 0, 0, 0]
            base[pivs[i]] = e
            rec2(0, base)
        rec(0, [])
    return out

def row_to_vecs(row, fb):
    """F2-basis (3 vectors in F2^28) of K.row embedded in the component"""
    vecs = []
    for lam in fb:
        v = 0
        for s in range(4):
            if row[s]:
                v ^= embed(mul7(lam, row[s]), s)
        vecs.append(v)
    return vecs

def sub_to_vecs(rows, fb):
    vecs = []
    for r in rows:
        vecs += row_to_vecs(r, fb)
    return vecs

# sanity: Vp x Vp and Vq x Vq vanish, V1 x Vp vanish
_vp_all = sub_to_vecs([(EP, 0, 0, 0), (0, EP, 0, 0), (0, 0, EP, 0), (0, 0, 0, EP)], BKP)
_vq_all = sub_to_vecs([(EQ, 0, 0, 0), (0, EQ, 0, 0), (0, 0, EQ, 0), (0, 0, 0, EQ)], BKQ)
for u in _vp_all:
    for v in _vp_all:
        assert sp(u, v) == 0
for u in _vq_all:
    for v in _vq_all:
        assert sp(u, v) == 0
for t in triv:
    for v in _vp_all + _vq_all:
        assert sp(t, v) == 0

SWAP = lambda u: ((u & ((1 << 14) - 1)) << 14) | (u >> 14)

only_dp = int(sys.argv[1]) if len(sys.argv) > 1 else None
total = 0
for dp in range(4):
    if only_dp is not None and dp != only_dp:
        continue
    dq = 3 - dp
    Ups = subspaces(KP, dp)
    Uqs = subspaces(KQ, dq)
    # precompute F2 vecs
    Upv = [sub_to_vecs(rows, BKP) for rows in Ups]
    Uqv = [sub_to_vecs(rows, BKQ) for rows in Uqs]
    # swapped masks for orthogonality
    Upm = [[SWAP(v) for v in vs] for vs in Upv]
    npairs = 0
    for iu, (uv, um) in enumerate(zip(Upv, Upm)):
        for wv in Uqv:
            ok = True
            for m in um:
                for w in wv:
                    if bin(m & w).count('1') & 1:
                        ok = False
                        break
                if not ok:
                    break
            if not ok:
                continue
            npairs += 1
            for (l1, l2) in lagr:
                basis = [l1, l2] + uv + wv
                print(' '.join(f'{g:07x}' for g in basis))
                total += 1
    print(f"dp={dp}: |Up|={len(Ups)} |Uq|={len(Uqs)} orth pairs={npairs}",
          file=sys.stderr)
print(f"total emitted: {total}", file=sys.stderr)
